ENV_CFG = {
    "num_actions": 6,
    "default_joint_angles": {
        "shoulder_pan_joint": 0.0,
        "shoulder_lift_joint": -2.10,
        "elbow_joint": 2.10,
        "wrist_1_joint": -1.57,
        "wrist_2_joint": -1.57,
        "wrist_3_joint": 0.0,
        # "robotiq_hande_left_finger_joint": 0.025,
        # "robotiq_hande_right_finger_joint": 0.025,
    },
    "dof_names": [
        'shoulder_pan_joint',
        'shoulder_lift_joint',
        'elbow_joint',
        'wrist_1_joint',
        'wrist_2_joint',
        'wrist_3_joint',
        # 'robotiq_hande_left_finger_joint',
        # 'robotiq_hande_right_finger_joint',
    ],
    "kp": [600, 600, 400, 400, 200, 200],
    "kd": [60, 60, 40, 40, 20, 20],
    "robot_pos": [0.0, 0.0, 0.0],
    "table_pos": [0.0, 0.6, 0.41],
    "object_spawn_x": [-0.36, -0.24],
    "object_spawn_y": [0.34, 0.66],
    "object_spawn_z": [0.84, 0.85],
    "target_pos": [-0.1, 0.76, 0.84],
    "target_threshold": 0.06,
    "episode_length_s": 5.0,
    "dt": 0.05,
    "action_scale": 0.5,
    "clip_actions": 100.0,
    "num_obs": 24,
        "obs_scales": {
            "dof_pos": 1.0,
            "dof_vel": 0.1,
        },
    "reward_scales": {
        "near": -0.5,
        "dist": -1.0,
        "control": -0.1,
    },
}